/**
 * Phase 25 Plan 02: Fallback Plan Creation from Research Data
 *
 * Creates Plan records for all providers without plans, using pricing data
 * sourced from v3-pricing-data.md research and reasonable estimates.
 *
 * This script is used when xAI API credits are exhausted (429 errors).
 * It follows the same patterns as 25-create-plans.ts but uses hardcoded data.
 *
 * Run with: npx tsx prisma/scripts/25-create-plans-fallback.ts
 * Dry run:  npx tsx prisma/scripts/25-create-plans-fallback.ts --dry-run
 * Single:   npx tsx prisma/scripts/25-create-plans-fallback.ts --slug=dinnerly
 */

import "dotenv/config";
import { config } from "dotenv";
import { PrismaClient } from "../../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import type { PlanFrequency } from "../../src/generated/prisma/client";

config({ path: ".env.local" });

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// ─── Types ──────────────────────────────────────────────────────────────────

interface PlanInput {
  name: string;
  description: string;
  pricePerServingCents: number | null;
  pricePerBoxCents: number | null;
  pricePerWeekCents: number | null;
  shippingCostCents: number;
  shippingNote: string | null;
  introOfferNote: string | null;
  servingsPerMeal: number | null;
  mealsPerWeek: number | null;
  frequency: PlanFrequency;
  featured: boolean;
}

type ProviderPlansMap = Record<string, PlanInput[]>;

// ─── Hardcoded Plan Data ────────────────────────────────────────────────────
// Sources: v3-pricing-data.md research, provider websites, review sites

const MEAL_KIT_PLANS: ProviderPlansMap = {
  "dinnerly": [
    {
      name: "2 People, 3 Meals/Week",
      description: "Budget-friendly meal kit with simple recipes and fewer ingredients. Great for couples.",
      pricePerServingCents: 699,
      pricePerBoxCents: 4194,
      pricePerWeekCents: null,
      shippingCostCents: 1099,
      shippingNote: "$10.99 flat rate",
      introOfferNote: "50% off first box",
      servingsPerMeal: 2,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "4 People, 3 Meals/Week",
      description: "Family-sized meal kit with easy-to-follow recipes. Feeds a family of 4.",
      pricePerServingCents: 599,
      pricePerBoxCents: 7188,
      pricePerWeekCents: null,
      shippingCostCents: 1099,
      shippingNote: "$10.99 flat rate",
      introOfferNote: "50% off first box",
      servingsPerMeal: 4,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "gobble": [
    {
      name: "2 People, 3 Meals/Week",
      description: "Semi-prepped meal kit ready in 15 minutes. Pre-chopped vegetables and marinated proteins.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 7194,
      pricePerWeekCents: null,
      shippingCostCents: 999,
      shippingNote: "$9.99 flat rate",
      introOfferNote: "50% off first box",
      servingsPerMeal: 2,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "4 People, 3 Meals/Week",
      description: "Family-sized Gobble box with 15-minute prep time. Perfect for busy families.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 13188,
      pricePerWeekCents: null,
      shippingCostCents: 999,
      shippingNote: "$9.99 flat rate",
      introOfferNote: "50% off first box",
      servingsPerMeal: 4,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "marley-spoon": [
    {
      name: "2 People, 3 Meals/Week",
      description: "Premium meal kit by Martha Stewart with restaurant-quality recipes and fresh ingredients.",
      pricePerServingCents: 1025,
      pricePerBoxCents: 6150,
      pricePerWeekCents: null,
      shippingCostCents: 1099,
      shippingNote: "$8.99-$11.99",
      introOfferNote: "50% off first box + free shipping",
      servingsPerMeal: 2,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "4 People, 3 Meals/Week",
      description: "Family-sized Martha Stewart meal kit with fresh ingredients and step-by-step recipes.",
      pricePerServingCents: 899,
      pricePerBoxCents: 10788,
      pricePerWeekCents: null,
      shippingCostCents: 1099,
      shippingNote: "$8.99-$11.99",
      introOfferNote: "50% off first box + free shipping",
      servingsPerMeal: 4,
      mealsPerWeek: 3,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
};

const PREPARED_MEAL_PLANS: ProviderPlansMap = {
  "bistromd": [
    {
      name: "5-Day Program",
      description: "Doctor-designed weight loss meals. Includes lunch and dinner for 5 days with optional breakfast add-on.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 14000,
      pricePerWeekCents: 14000,
      shippingCostCents: 1995,
      shippingNote: "$19.95 per shipment",
      introOfferNote: "25% off first week",
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "7-Day Full Program",
      description: "Complete 7-day weight loss program with breakfast, lunch, dinner and snacks. Doctor-designed for optimal nutrition.",
      pricePerServingCents: 999,
      pricePerBoxCents: 22000,
      pricePerWeekCents: 22000,
      shippingCostCents: 1995,
      shippingNote: "$19.95 per shipment",
      introOfferNote: "25% off first week",
      servingsPerMeal: 1,
      mealsPerWeek: 21,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "clean-eatz-kitchen": [
    {
      name: "6 Meals/Week",
      description: "Healthy prepared meals with balanced macros. Choose from a rotating weekly menu of fresh entrees.",
      pricePerServingCents: 899,
      pricePerBoxCents: 5394,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 6,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "12 Meals/Week",
      description: "Full week of clean eating with 12 chef-prepared meals. Great for meal prep.",
      pricePerServingCents: 799,
      pricePerBoxCents: 9588,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 12,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "daily-harvest": [
    {
      name: "9 Items/Week",
      description: "Plant-based smoothies, harvest bowls, flatbreads, and more. Choose from 80+ items built on fruits and vegetables.",
      pricePerServingCents: 899,
      pricePerBoxCents: 8091,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "Up to $40 off first box",
      servingsPerMeal: 1,
      mealsPerWeek: 9,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "14 Items/Week",
      description: "Our most popular plan. Mix and match smoothies, bowls, soups, and more for a full week of plant-based meals.",
      pricePerServingCents: 799,
      pricePerBoxCents: 11186,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "Up to $40 off first box",
      servingsPerMeal: 1,
      mealsPerWeek: 14,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "24 Items/Week",
      description: "Best value plan with 24 items per delivery. Perfect for families or full meal prep.",
      pricePerServingCents: 699,
      pricePerBoxCents: 16776,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "Up to $40 off first box",
      servingsPerMeal: 1,
      mealsPerWeek: 24,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "eat-clean-bro": [
    {
      name: "10 Meals/Week",
      description: "Fresh, never frozen prepared meals with clean ingredients. No contracts, skip or cancel anytime.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 10990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "icon-meals": [
    {
      name: "8 Meals/Week",
      description: "Custom macro-counted meals for fitness enthusiasts. Choose your protein, carb, and veggie combination.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 8792,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: "15% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 8,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "14 Meals/Week",
      description: "Full meal prep solution with 14 custom macro-counted meals delivered fresh.",
      pricePerServingCents: 999,
      pricePerBoxCents: 13986,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: "15% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 14,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "magickitchen-com": [
    {
      name: "7 Meals Bundle",
      description: "Home-style prepared meals for seniors and those with dietary restrictions. Chef-prepared and flash frozen.",
      pricePerServingCents: 1299,
      pricePerBoxCents: 9093,
      pricePerWeekCents: null,
      shippingCostCents: 1999,
      shippingNote: "$19.99 shipping; free on orders $100+",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 7,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "mealpro": [
    {
      name: "10 Meals/Week",
      description: "Macro-balanced meals for fitness goals. Choose from muscle gain, weight loss, or keto menus.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 11990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: "10% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "megafit-meals": [
    {
      name: "10 Meals/Week",
      description: "Performance-focused prepared meals with precise macros. Popular with athletes and fitness enthusiasts.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 10990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "methodology": [
    {
      name: "5 Meals/Week",
      description: "Chef-crafted organic meals made with locally sourced ingredients. Premium quality, delivered fresh.",
      pricePerServingCents: 1599,
      pricePerBoxCents: 7995,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 5,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "10 Meals/Week",
      description: "Full week of chef-prepared organic meals. Seasonal menus with premium ingredients.",
      pricePerServingCents: 1399,
      pricePerBoxCents: 13990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "modifyhealth": [
    {
      name: "6 Meals/Week",
      description: "Gut-health focused meals designed by dietitians. Low FODMAP and Mediterranean diet options.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 7194,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "10% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 6,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "12 Meals/Week",
      description: "Complete meal plan for gut health. Dietitian-designed low FODMAP and Mediterranean diet meals.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 13188,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "10% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 12,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "moms-meals": [
    {
      name: "7 Meals/Week",
      description: "Nutritious meals for seniors and those on Medicare. Dietitian-approved with special diet options available.",
      pricePerServingCents: 799,
      pricePerBoxCents: 5593,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping; may be covered by Medicare/Medicaid",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 7,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "14 Meals/Week",
      description: "Full 2-meal-a-day plan for seniors. Includes lunch and dinner with special diet options.",
      pricePerServingCents: 699,
      pricePerBoxCents: 9786,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping; may be covered by Medicare/Medicaid",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 14,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "nutrisystem": [
    {
      name: "Basic Plan",
      description: "28-day structured weight loss program with ready-to-eat meals. Includes breakfast, lunch, dinner and snacks.",
      pricePerServingCents: 839,
      pricePerBoxCents: null,
      pricePerWeekCents: 5873,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: "50% off + free shipping",
      servingsPerMeal: 1,
      mealsPerWeek: 21,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "Uniquely Yours Plan",
      description: "Most popular 28-day weight loss program with frozen and non-frozen meals. Over 160 menu choices.",
      pricePerServingCents: 1099,
      pricePerBoxCents: null,
      pricePerWeekCents: 7693,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: "50% off + free shipping",
      servingsPerMeal: 1,
      mealsPerWeek: 21,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "sakara-life": [
    {
      name: "3-Day Reset",
      description: "Luxury plant-based organic meal program with breakfast, lunch and dinner for 3 days.",
      pricePerServingCents: 2500,
      pricePerBoxCents: null,
      pricePerWeekCents: 16100,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 9,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "5-Day Signature Program",
      description: "Full 5-day luxury organic meal program with all meals and snacks. The complete Sakara experience.",
      pricePerServingCents: 3300,
      pricePerBoxCents: null,
      pricePerWeekCents: 42000,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 15,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "splendid-spoon": [
    {
      name: "Lunch Plan",
      description: "5 plant-based soups and grain bowls per week. Ready to heat and eat in minutes.",
      pricePerServingCents: 999,
      pricePerBoxCents: 4995,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: "15% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 5,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Lunch + Dinner Plan",
      description: "10 plant-based meals per week including soups, bowls, and noodle dishes.",
      pricePerServingCents: 899,
      pricePerBoxCents: 8990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: "15% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "sprinly": [
    {
      name: "6 Meals/Week",
      description: "100% plant-based organic prepared meals. Chef-crafted with seasonal ingredients.",
      pricePerServingCents: 1599,
      pricePerBoxCents: 9594,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 6,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "tempo": [
    {
      name: "6 Meals/Week",
      description: "Protein-focused prepared meals for active lifestyles. Fresh, never frozen.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 7194,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "20% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 6,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "12 Meals/Week",
      description: "Full week of high-protein prepared meals. Perfect for meal prep and fitness goals.",
      pricePerServingCents: 1099,
      pricePerBoxCents: 13188,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "20% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 12,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "territory-foods": [
    {
      name: "6 Meals/Week",
      description: "Chef-network prepared meals made with whole food ingredients. Choose from multiple dietary preferences.",
      pricePerServingCents: 1399,
      pricePerBoxCents: 8394,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 6,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "10 Meals/Week",
      description: "Complete meal coverage with chef-prepared meals from a network of local chefs.",
      pricePerServingCents: 1299,
      pricePerBoxCents: 12990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "veestro": [
    {
      name: "10 Meals",
      description: "Chef-prepared 100% plant-based meals. Frozen for freshness, microwave-ready in minutes.",
      pricePerServingCents: 1199,
      pricePerBoxCents: 11990,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "30% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 10,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "20 Meals",
      description: "Best value plan with 20 plant-based prepared meals. Stock your freezer for easy meal prep.",
      pricePerServingCents: 999,
      pricePerBoxCents: 19980,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "30% off first order",
      servingsPerMeal: 1,
      mealsPerWeek: 20,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
};

const PROTEIN_BOX_PLANS: ProviderPlansMap = {
  "alaska-gold-seafood": [
    {
      name: "Wild Salmon Box",
      description: "Premium wild-caught Alaskan salmon delivered frozen. Sustainably harvested from Bristol Bay.",
      pricePerServingCents: null,
      pricePerBoxCents: 14900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "alaskan-salmon-company": [
    {
      name: "Monthly Salmon Box",
      description: "Wild-caught Alaskan salmon fillets delivered monthly. Sustainably harvested, flash frozen.",
      pricePerServingCents: null,
      pricePerBoxCents: 12900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "dartagnan": [
    {
      name: "Curated Meat Box",
      description: "Premium heritage breed meats including duck, lamb, and specialty cuts. Restaurant-quality proteins.",
      pricePerServingCents: null,
      pricePerBoxCents: 15900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $100+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "fish-fixe": [
    {
      name: "Wild Seafood Box",
      description: "Curated wild-caught seafood box with 5-7 servings of fish and shellfish. Perfect for weekly seafood meals.",
      pricePerServingCents: null,
      pricePerBoxCents: 9900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "fulton-fish-market": [
    {
      name: "Monthly Fish Box",
      description: "Premium seafood from NYC's Fulton Fish Market. Chef-curated selection of wild and sustainably farmed fish.",
      pricePerServingCents: null,
      pricePerBoxCents: 12900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $100+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "meat-n-bone": [
    {
      name: "Butcher's Box",
      description: "Premium cuts of beef, pork, and poultry. Sourced from small farms with responsible practices.",
      pricePerServingCents: null,
      pricePerBoxCents: 12900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $99+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "moink": [
    {
      name: "Sampler Box",
      description: "Grass-fed beef, heritage pork, pastured chicken, and wild-caught salmon. Ethical and sustainable.",
      pricePerServingCents: null,
      pricePerBoxCents: 12900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Full Box",
      description: "Full-size Moink box with 2x the protein. Grass-fed, pastured, and wild-caught proteins.",
      pricePerServingCents: null,
      pricePerBoxCents: 15900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "omaha-steaks": [
    {
      name: "Classic Assortment",
      description: "Iconic Omaha Steaks assortment including filet mignons, burgers, and gourmet sides.",
      pricePerServingCents: null,
      pricePerBoxCents: 14999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on select packages",
      introOfferNote: "Introductory packages available",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Package",
      description: "Premium selection of aged steaks, seafood, and gourmet sides. Perfect for special occasions.",
      pricePerServingCents: null,
      pricePerBoxCents: 24999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on select packages",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: false,
    },
  ],
  "porter-road": [
    {
      name: "Butcher's Bundle",
      description: "Pasture-raised meats from a Nashville butcher shop. Dry-aged beef, heritage pork, and more.",
      pricePerServingCents: null,
      pricePerBoxCents: 10000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Large Bundle",
      description: "Larger selection of pasture-raised meats. Perfect for families or stocking the freezer.",
      pricePerServingCents: null,
      pricePerBoxCents: 19900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "primal-pastures": [
    {
      name: "Monthly Meat Box",
      description: "100% pasture-raised meats from a regenerative farm. Chicken, beef, pork, and lamb.",
      pricePerServingCents: null,
      pricePerBoxCents: 14900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "rastellis": [
    {
      name: "Essential Box",
      description: "Premium proteins including USDA Choice steaks, chicken breasts, and seafood. Flash frozen for freshness.",
      pricePerServingCents: null,
      pricePerBoxCents: 6900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $200+; $10 for $100-199",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Box",
      description: "Premium selection of USDA Prime steaks, wild-caught seafood, and specialty proteins.",
      pricePerServingCents: null,
      pricePerBoxCents: 19900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $200+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "sea-to-table": [
    {
      name: "Monthly Seafood Box",
      description: "Wild-caught, traceable seafood from American fishermen. Sustainable and responsibly sourced.",
      pricePerServingCents: null,
      pricePerBoxCents: 9900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "seabear": [
    {
      name: "Wild Salmon Collection",
      description: "Premium smoked and wild salmon products from the Pacific Northwest. Ready-to-eat seafood gifts and boxes.",
      pricePerServingCents: null,
      pricePerBoxCents: 7900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $75+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
  ],
  "sitka-seafood-market": [
    {
      name: "Premium Fish Share",
      description: "Wild-caught Alaskan seafood harvested by community fishermen. Salmon, halibut, cod, and more.",
      pricePerServingCents: null,
      pricePerBoxCents: 16500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "sizzlefish": [
    {
      name: "Monthly Seafood Box",
      description: "Premium wild-caught and sustainably farmed fish delivered to your door. Portion-controlled fillets.",
      pricePerServingCents: null,
      pricePerBoxCents: 9900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "snake-river-farms": [
    {
      name: "American Wagyu Box",
      description: "Premium American Wagyu beef and Kurobuta pork. Some of the finest domestic beef available.",
      pricePerServingCents: null,
      pricePerBoxCents: 19900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $199+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
  ],
  "us-wellness-meats": [
    {
      name: "Grassfed Beef Box",
      description: "100% grass-fed, grass-finished beef from small family farms. No hormones, no antibiotics.",
      pricePerServingCents: null,
      pricePerBoxCents: 14900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $199+; $9.50 otherwise",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "vital-choice": [
    {
      name: "Wild Seafood Box",
      description: "Wild-caught Alaskan salmon, fish, and shellfish. MSC certified sustainable seafood.",
      pricePerServingCents: null,
      pricePerBoxCents: 12900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $99+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "wild-alaskan-company": [
    {
      name: "Wild Salmon Box",
      description: "Wild-caught Alaskan sockeye salmon. 6 oz portions, sustainably harvested.",
      pricePerServingCents: null,
      pricePerBoxCents: 13200,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "$25 off first box",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Wild Combo Box",
      description: "Mix of wild salmon, halibut, and cod. Premium Alaskan seafood variety pack.",
      pricePerServingCents: null,
      pricePerBoxCents: 26700,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "$25 off first box",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "wild-fork-foods": [
    {
      name: "Protein Bundle",
      description: "Curated selection of premium meats and seafood at wholesale prices. Flash frozen for freshness.",
      pricePerServingCents: null,
      pricePerBoxCents: 9900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $99+; $7.99 otherwise",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
  ],
  "wild-pastures": [
    {
      name: "Family Box",
      description: "100% pasture-raised and grass-fed meats. Includes beef, chicken, pork and wild-caught seafood.",
      pricePerServingCents: null,
      pricePerBoxCents: 13900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "$25 off first box",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "wild-tide-seafoods": [
    {
      name: "Wild Seafood Share",
      description: "Wild-caught Pacific Northwest seafood. Sustainably harvested, frozen at sea for peak freshness.",
      pricePerServingCents: null,
      pricePerBoxCents: 11900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
};

const PRODUCE_BOX_PLANS: ProviderPlansMap = {
  "baldor-specialty-foods": [
    {
      name: "Seasonal Produce Box",
      description: "Premium specialty produce sourced from top farms. Restaurant-quality fruits and vegetables for home cooks.",
      pricePerServingCents: null,
      pricePerBoxCents: 5500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area (NYC metro)",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "bountiful-baskets-food-co-op": [
    {
      name: "Conventional Basket",
      description: "Community food co-op produce basket with seasonal fruits and vegetables at below-retail prices.",
      pricePerServingCents: null,
      pricePerBoxCents: 2500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Pickup at community location",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Organic Basket",
      description: "All-organic produce basket from the co-op. Seasonal fruits and vegetables at co-op prices.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Pickup at community location",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "farm-fresh-to-you": [
    {
      name: "Small Mixed Box",
      description: "CSA-style box with a mix of seasonal fruits and vegetables from California organic farms.",
      pricePerServingCents: null,
      pricePerBoxCents: 3300,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Delivery included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "Regular Mixed Box",
      description: "Full-sized CSA box with a generous selection of seasonal organic produce. Feeds a family of 3-4.",
      pricePerServingCents: null,
      pricePerBoxCents: 4200,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Delivery included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "farm-to-people": [
    {
      name: "Farm Share Box",
      description: "Curated selection of locally sourced produce, dairy, and artisan goods from small farms.",
      pricePerServingCents: null,
      pricePerBoxCents: 5000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in NYC area",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "farmbox-california": [
    {
      name: "Organic Produce Box",
      description: "California-grown organic produce delivered weekly. Fresh from farm to table.",
      pricePerServingCents: null,
      pricePerBoxCents: 3900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "frog-hollow-farm": [
    {
      name: "Seasonal Fruit Box",
      description: "Premium organic stone fruits and tree-ripened fruit from Frog Hollow Farm in Brentwood, CA.",
      pricePerServingCents: null,
      pricePerBoxCents: 4500,
      pricePerWeekCents: null,
      shippingCostCents: 999,
      shippingNote: "$9.99 shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "full-circle": [
    {
      name: "Organic Produce Box",
      description: "Customizable organic produce box with seasonal fruits and vegetables. Pacific Northwest farm-fresh.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "harry-and-david": [
    {
      name: "Monthly Fruit Club",
      description: "Premium fruit gifts and seasonal fruit boxes. Famous for Royal Riviera pears and specialty fruits.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on select items",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Deluxe Fruit Club",
      description: "Larger monthly fruit selection with premium varieties and seasonal specialties.",
      pricePerServingCents: null,
      pricePerBoxCents: 5999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on select items",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "hungry-harvest": [
    {
      name: "Mini Harvest",
      description: "Rescued produce box with 6-7 seasonal fruits and vegetables. Fights food waste with affordable produce.",
      pricePerServingCents: null,
      pricePerBoxCents: 1500,
      pricePerWeekCents: null,
      shippingCostCents: 349,
      shippingNote: "Free on orders $29.99+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "Full Harvest",
      description: "Our most popular box with 7-9 items of rescued seasonal produce. Great for a family of 2-3.",
      pricePerServingCents: null,
      pricePerBoxCents: 2500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Super Harvest",
      description: "Large rescued produce box with 10-12 items. Feeds a family of 4+ and saves the most food from waste.",
      pricePerServingCents: null,
      pricePerBoxCents: 3300,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "imperfect-foods": [
    {
      name: "Weekly Grocery Box",
      description: "Online grocery with rescued and surplus produce, pantry items, and proteins at up to 30% off retail.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 599,
      shippingNote: "Free on orders $60+; $5.99 delivery fee",
      introOfferNote: "20% off first order",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "market-wagon": [
    {
      name: "Weekly Market Order",
      description: "Online farmers market connecting you directly with local farmers, ranchers, and artisan producers.",
      pricePerServingCents: null,
      pricePerBoxCents: 4000,
      pricePerWeekCents: null,
      shippingCostCents: 599,
      shippingNote: "$5.99 delivery fee",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "melissas-produce": [
    {
      name: "Exotic Produce Box",
      description: "Specialty and exotic produce from around the world. Discover unique fruits and vegetables.",
      pricePerServingCents: null,
      pricePerBoxCents: 4999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $49+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "miami-fruit": [
    {
      name: "Tropical Fruit Box",
      description: "Premium tropical fruits from Florida and the Caribbean. Tree-ripened mangos, dragon fruit, and more.",
      pricePerServingCents: null,
      pricePerBoxCents: 14700,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping varies by location",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Tropical Box",
      description: "Large box of premium tropical fruits including rare varieties. A true tropical fruit experience.",
      pricePerServingCents: null,
      pricePerBoxCents: 20000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping varies by location",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: false,
    },
  ],
  "norwich-meadows-farm": [
    {
      name: "CSA Farm Share",
      description: "Community-supported agriculture share from a certified organic farm in Norwich, NY.",
      pricePerServingCents: null,
      pricePerBoxCents: 4000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Pickup at NYC farmers market locations",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "talley-farms-box": [
    {
      name: "Farm Produce Box",
      description: "Fresh produce from Talley Farms on California's Central Coast. Seasonal vegetables and fruits.",
      pricePerServingCents: null,
      pricePerBoxCents: 3000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Local delivery in SLO/SB counties",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "the-fruitguys": [
    {
      name: "Office Fruit Box",
      description: "Fresh fruit deliveries for offices and homes. Seasonal, organic options available.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "the-produce-box": [
    {
      name: "Standard Produce Box",
      description: "Farm-fresh local produce delivered weekly. Seasonal fruits and vegetables from regional farms.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free delivery in service area",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "the-urban-canopy": [
    {
      name: "Community Farm Box",
      description: "Urban farm produce box supporting local and sustainable agriculture in Chicago.",
      pricePerServingCents: null,
      pricePerBoxCents: 3000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Pickup or local delivery",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "WEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
};

const SPECIALTY_PLANS: ProviderPlansMap = {
  "amazing-clubs": [
    {
      name: "Monthly Subscription",
      description: "Choose from 40+ club themes including beer, wine, cheese, chocolate, and more. Curated selections each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "atlas-coffee-club": [
    {
      name: "Half Bag",
      description: "Single-origin coffee from a different country each month. Half bag (6 oz) of freshly roasted beans.",
      pricePerServingCents: null,
      pricePerBoxCents: 1450,
      pricePerWeekCents: null,
      shippingCostCents: 495,
      shippingNote: "$4.95 shipping",
      introOfferNote: "First bag from $9",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "Full Bag",
      description: "Full 12 oz bag of single-origin coffee from a new country each month. Our most popular plan.",
      pricePerServingCents: null,
      pricePerBoxCents: 2950,
      pricePerWeekCents: null,
      shippingCostCents: 495,
      shippingNote: "$4.95 shipping",
      introOfferNote: "First bag from $14",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "bean-box": [
    {
      name: "Coffee Sampler",
      description: "4 specialty coffee samples from top Seattle roasters. Discover new favorites every month.",
      pricePerServingCents: null,
      pricePerBoxCents: 2399,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "blue-bottle-coffee": [
    {
      name: "Single Origin Subscription",
      description: "Freshly roasted single-origin coffee shipped within 24 hours of roasting. From Blue Bottle's expert roasters.",
      pricePerServingCents: null,
      pricePerBoxCents: 2200,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Blend Subscription",
      description: "Signature blend coffee from Blue Bottle. Consistent, delicious coffee on a schedule that works for you.",
      pricePerServingCents: null,
      pricePerBoxCents: 1800,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "bokksu": [
    {
      name: "Classic Box",
      description: "20-24 authentic Japanese snacks and teas curated around a cultural theme. Includes tasting guide.",
      pricePerServingCents: null,
      pricePerBoxCents: 4999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on subscriptions",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "cheryls": [
    {
      name: "Cookie Club",
      description: "Famous buttercream-frosted cookies delivered monthly. A sweet gift that keeps giving.",
      pricePerServingCents: null,
      pricePerBoxCents: 3499,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "cometeer": [
    {
      name: "Mixed Roast Box",
      description: "Flash-frozen specialty coffee capsules from top roasters. Just melt in hot water or milk. 32 capsules per box.",
      pricePerServingCents: null,
      pricePerBoxCents: 6400,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "50% off first box",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Dark Roast Box",
      description: "32 dark roast flash-frozen coffee capsules from award-winning specialty roasters.",
      pricePerServingCents: null,
      pricePerBoxCents: 6400,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "50% off first box",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "craft-jerky-co": [
    {
      name: "Monthly Jerky Box",
      description: "Artisan craft jerky from small-batch producers. 4-6 unique flavors curated monthly.",
      pricePerServingCents: null,
      pricePerBoxCents: 2599,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "driftaway-coffee": [
    {
      name: "Coffee Subscription",
      description: "Personalized single-origin coffee based on your taste profile. Freshly roasted and shipped.",
      pricePerServingCents: null,
      pricePerBoxCents: 1700,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: "Start with an Explorer Kit",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "fuego-box": [
    {
      name: "Monthly Hot Sauce Box",
      description: "3 artisan hot sauces from small-batch producers. Discover new flavors and heat levels each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 2999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "heat-hot-sauce-shop": [
    {
      name: "Hot Sauce of the Month",
      description: "Curated artisan hot sauce from a different small-batch producer each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 1499,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "heatonist": [
    {
      name: "Hot Ones Box",
      description: "Hot sauce subscription featuring sauces from the Hot Ones show. 3 sauces per quarterly shipment.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "japan-crate": [
    {
      name: "Japan Crate",
      description: "Japanese candy, snacks, and drinks curated monthly. Unique items imported directly from Japan.",
      pricePerServingCents: null,
      pricePerBoxCents: 3500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Japan Crate",
      description: "Larger selection of Japanese snacks, candy, and exclusive items. Premium experience with 15+ items.",
      pricePerServingCents: null,
      pricePerBoxCents: 4800,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "jenis-splendid-ice-creams": [
    {
      name: "Pint Collection",
      description: "Award-winning artisan ice cream shipped in 4-pint collections. Unique and creative flavors.",
      pricePerServingCents: null,
      pricePerBoxCents: 6800,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $55+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "ketokrate": [
    {
      name: "Monthly Keto Box",
      description: "10+ keto-friendly snacks curated monthly. All items under 5g net carbs per serving.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "levain-bakery": [
    {
      name: "Cookie Box",
      description: "Famous oversized gourmet cookies from NYC's Levain Bakery. Shipped fresh nationwide.",
      pricePerServingCents: null,
      pricePerBoxCents: 4500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping varies by location",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
  ],
  "love-me-gluten-free": [
    {
      name: "Monthly Gluten-Free Box",
      description: "Curated gluten-free snacks and treats. Discover new safe-to-eat products each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 3499,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "milk-bar": [
    {
      name: "Treats Assortment",
      description: "Famous Milk Bar treats including cookies, cakes, and truffles. From the award-winning NYC bakery.",
      pricePerServingCents: null,
      pricePerBoxCents: 5500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on orders $50+",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "FLEXIBLE" as PlanFrequency,
      featured: true,
    },
  ],
  "misto": [
    {
      name: "MistoBox Subscription",
      description: "Personalized coffee subscription matched to your taste preferences. From 500+ top roasters.",
      pricePerServingCents: null,
      pricePerBoxCents: 1595,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: true,
    },
  ],
  "munch-addict": [
    {
      name: "Monthly Snack Box",
      description: "International snack box with treats from around the world. 10-15 unique snacks per box.",
      pricePerServingCents: null,
      pricePerBoxCents: 2999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "munchpak": [
    {
      name: "MunchPak Original",
      description: "International snack box with 10+ snacks from different countries. Discover global flavors.",
      pricePerServingCents: null,
      pricePerBoxCents: 2495,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "MunchPak Family",
      description: "Larger snack box with 20+ international snacks. Perfect for sharing with the whole family.",
      pricePerServingCents: null,
      pricePerBoxCents: 4495,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "murrays-cheese": [
    {
      name: "Monthly Cheese Club",
      description: "Curated artisan cheeses from Murray's legendary cheese caves. Includes tasting notes.",
      pricePerServingCents: null,
      pricePerBoxCents: 5500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "olive-oil-lovers": [
    {
      name: "Discovery Club",
      description: "Premium extra virgin olive oils from world-class producers. Discover artisan oils each quarter.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "piquant-post": [
    {
      name: "Monthly Spice Kit",
      description: "Global spice blends and recipes from a new cuisine each month. Includes recipe cards and info.",
      pricePerServingCents: null,
      pricePerBoxCents: 1199,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "rawspicebar": [
    {
      name: "Monthly Spice Club",
      description: "Freshly ground spice kit with recipes. Explore a new cuisine each month with hand-blended spices.",
      pricePerServingCents: null,
      pricePerBoxCents: 1500,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "seoulbox": [
    {
      name: "Seoulbox Signature",
      description: "Curated Korean snacks, drinks, and treats. Discover the flavors of Seoul each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 3999,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "sips-by": [
    {
      name: "Monthly Tea Box",
      description: "Personalized tea subscription with 4 teas matched to your taste profile each month.",
      pricePerServingCents: null,
      pricePerBoxCents: 1600,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "snackcrate": [
    {
      name: "Mini Crate",
      description: "5-6 international snacks from a new country each month. A taste of global flavors.",
      pricePerServingCents: null,
      pricePerBoxCents: 1700,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
    {
      name: "Original Crate",
      description: "10-12 snacks from a new country each month. Our most popular size. Includes a drink.",
      pricePerServingCents: null,
      pricePerBoxCents: 2900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Crate",
      description: "18-20 international snacks from a new country each month. The ultimate snack experience.",
      pricePerServingCents: null,
      pricePerBoxCents: 5000,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Shipping included",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "snackfever": [
    {
      name: "Original Box",
      description: "Korean snacks and treats curated monthly. Authentic flavors imported directly from South Korea.",
      pricePerServingCents: null,
      pricePerBoxCents: 2800,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Deluxe Box",
      description: "Premium Korean snack box with 16+ items including full-size products and exclusive treats.",
      pricePerServingCents: null,
      pricePerBoxCents: 4200,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: false,
    },
  ],
  "snacksack": [
    {
      name: "Monthly Snack Sack",
      description: "Curated healthy and organic snacks delivered monthly. Better-for-you snacking made easy.",
      pricePerServingCents: null,
      pricePerBoxCents: 2299,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "tea-runners": [
    {
      name: "Monthly Tea Box",
      description: "Customizable premium tea subscription. Choose your preferred tea types and flavors.",
      pricePerServingCents: null,
      pricePerBoxCents: 2200,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US/CA shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "tokyotreat": [
    {
      name: "Classic Box",
      description: "17 full-size Japanese snacks, candy, and drinks. Exclusive items not available outside Japan.",
      pricePerServingCents: null,
      pricePerBoxCents: 3499,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free worldwide shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "trade-coffee": [
    {
      name: "Classics Subscription",
      description: "Freshly roasted coffee from 50+ top roasters. Matched to your taste preferences.",
      pricePerServingCents: null,
      pricePerBoxCents: 1699,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on prepaid/2lb+",
      introOfferNote: "First bag $8",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: true,
    },
    {
      name: "Premium Subscription",
      description: "Premium single-origin and limited-release coffees. For the serious coffee enthusiast.",
      pricePerServingCents: null,
      pricePerBoxCents: 2199,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping on prepaid/2lb+",
      introOfferNote: "First bag $8",
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "BIWEEKLY" as PlanFrequency,
      featured: false,
    },
  ],
  "try-the-world": [
    {
      name: "Snack Box",
      description: "International snacks and gourmet foods from a different country each month. Artisan selection.",
      pricePerServingCents: null,
      pricePerBoxCents: 3900,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "urthbox": [
    {
      name: "Classic Box",
      description: "Curated healthy and organic snacks delivered monthly. Discover new better-for-you brands.",
      pricePerServingCents: null,
      pricePerBoxCents: 2799,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
  "vegancuts-snack-box": [
    {
      name: "Monthly Vegan Snack Box",
      description: "10+ vegan snacks curated monthly. Discover new plant-based brands and flavors.",
      pricePerServingCents: null,
      pricePerBoxCents: 3299,
      pricePerWeekCents: null,
      shippingCostCents: 0,
      shippingNote: "Free US shipping",
      introOfferNote: null,
      servingsPerMeal: null,
      mealsPerWeek: null,
      frequency: "MONTHLY" as PlanFrequency,
      featured: true,
    },
  ],
};

// Merge all category maps
const ALL_PLANS: ProviderPlansMap = {
  ...MEAL_KIT_PLANS,
  ...PREPARED_MEAL_PLANS,
  ...PROTEIN_BOX_PLANS,
  ...PRODUCE_BOX_PLANS,
  ...SPECIALTY_PLANS,
};

// ─── CLI Argument Parsing ───────────────────────────────────────────────────

function parseArgs() {
  const args = process.argv.slice(2);
  return {
    dryRun: args.includes("--dry-run"),
    slug: args.find((a) => a.startsWith("--slug="))?.split("=")[1] ?? null,
  };
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const { dryRun, slug } = parseArgs();

  console.log(`\n=== Phase 25 Plan 02: Fallback Plan Creation ===`);
  console.log(`Mode: ${dryRun ? "DRY RUN" : "LIVE"}`);
  if (slug) console.log(`Filter: --slug=${slug}`);
  console.log("");

  // Get all providers without plans (or a specific slug)
  const where: Record<string, unknown> = {
    status: { not: "DISCONTINUED" },
  };

  if (slug) {
    where.slug = slug;
  } else {
    where.plans = { none: {} };
  }

  const providers = await prisma.provider.findMany({
    where,
    select: { id: true, slug: true, name: true, category: true },
    orderBy: [{ category: "asc" }, { slug: "asc" }],
  });

  console.log(`Providers to process: ${providers.length}`);

  if (providers.length === 0) {
    console.log("No providers to process. All have plans!");
    return;
  }

  let totalPlansCreated = 0;
  let providersProcessed = 0;
  let providersSkipped = 0;
  const skippedSlugs: string[] = [];

  for (const provider of providers) {
    const plans = ALL_PLANS[provider.slug];
    if (!plans || plans.length === 0) {
      console.log(`  SKIP: ${provider.slug} (${provider.name}) -- no hardcoded data`);
      providersSkipped++;
      skippedSlugs.push(provider.slug);
      continue;
    }

    console.log(`\nProcessing: ${provider.name} (${provider.slug}) [${provider.category}]`);

    if (dryRun) {
      console.log(`  [DRY RUN] Would create ${plans.length} plans`);
      for (const plan of plans) {
        console.log(`    "${plan.name}" -- serving: ${plan.pricePerServingCents}, box: ${plan.pricePerBoxCents}`);
      }
      totalPlansCreated += plans.length;
      providersProcessed++;
      continue;
    }

    // Delete existing plans for this provider (idempotent)
    const deleteResult = await prisma.plan.deleteMany({
      where: { providerId: provider.id },
    });
    if (deleteResult.count > 0) {
      console.log(`  Deleted ${deleteResult.count} existing plans`);
    }

    // Create each plan
    let created = 0;
    for (let i = 0; i < plans.length; i++) {
      const plan = plans[i];
      try {
        await prisma.plan.create({
          data: {
            providerId: provider.id,
            name: plan.name,
            description: plan.description,
            pricePerServingCents: plan.pricePerServingCents,
            pricePerBoxCents: plan.pricePerBoxCents,
            pricePerWeekCents: plan.pricePerWeekCents,
            shippingCostCents: plan.shippingCostCents,
            shippingNote: plan.shippingNote,
            introOfferNote: plan.introOfferNote,
            servingsPerMeal: plan.servingsPerMeal,
            mealsPerWeek: plan.mealsPerWeek,
            frequency: plan.frequency,
            featured: plan.featured,
            active: true,
            sortOrder: i,
          },
        });
        created++;
      } catch (err) {
        console.error(`  ERROR creating plan "${plan.name}": ${err}`);
      }
    }

    // Recompute denormalized fields on Provider
    const allPlans = await prisma.plan.findMany({
      where: { providerId: provider.id, active: true },
      select: { pricePerServingCents: true, shippingCostCents: true },
    });

    const servingPrices = allPlans
      .map((p) => p.pricePerServingCents)
      .filter((v): v is number => v !== null);

    const hasFreeShipping = allPlans.some((p) => p.shippingCostCents === 0);

    await prisma.provider.update({
      where: { id: provider.id },
      data: {
        minPricePerServingCents: servingPrices.length > 0 ? Math.min(...servingPrices) : null,
        maxPricePerServingCents: servingPrices.length > 0 ? Math.max(...servingPrices) : null,
        freeShipping: hasFreeShipping,
      },
    });

    console.log(`  Created ${created} plans, denormalized fields updated`);
    totalPlansCreated += created;
    providersProcessed++;
  }

  // Print summary
  console.log(`\n=== Fallback Plan Creation Complete ===`);
  console.log(`Providers processed: ${providersProcessed}`);
  console.log(`Plans created: ${totalPlansCreated}`);
  console.log(`Providers skipped (no data): ${providersSkipped}`);

  if (skippedSlugs.length > 0) {
    console.log(`\nSkipped slugs (need xAI API or manual research):`);
    for (const s of skippedSlugs) {
      console.log(`  ${s}`);
    }
  }

  console.log("");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
