import Image from "next/image";

export const metadata = {
  title: "Logo Gallery",
};

const logos = [
  { file: "01-clean-sans-leaf.jpg", label: "Clean Sans + Leaf", desc: "Modern sans-serif, open box with leaf, green & charcoal" },
  { file: "02-bold-meat-salmon.jpg", label: "Bold Meat & Salmon", desc: "Chunky rounded font, salmon & steak in box, warm orange/red" },
  { file: "03-vintage-badge-seal.jpg", label: "Vintage Badge Seal", desc: "Circular seal, crossed fork/knife over box, navy & gold" },
  { file: "04-ultra-minimal-type.jpg", label: "Ultra Minimal Type", desc: "Thin sans-serif, box replaces letterform, single teal accent" },
  { file: "05-stacked-editorial.jpg", label: "Stacked Editorial", desc: "Uppercase slab-serif stacked, lobster between lines, navy & coral" },
  { file: "06-friendly-tumbling.jpg", label: "Friendly Tumbling", desc: "Bubbly font, fish/apple/broccoli tumbling from box, colorful" },
  { file: "07-brush-artisanal.jpg", label: "Brush Artisanal", desc: "Brush script, line-drawn box with steak/shrimp/herbs, brown ink" },
  { file: "08-tech-geometric.jpg", label: "Tech Geometric", desc: "Lowercase geometric sans, abstract overlapping squares icon, teal & coral" },
  { file: "09-split-color-wordmark.jpg", label: "Split Color Wordmark", desc: "Food=orange, Box=green, Finder=gray, illustrated box above" },
  { file: "10-retro-diner.jpg", label: "Retro Diner", desc: "1950s font, food icons around box, mustard/brick/olive" },
  { file: "11-monoline-drumstick.jpg", label: "Monoline Drumstick", desc: "Single continuous stroke forming box + chicken, light sans below" },
  { file: "12-bold-condensed-heart.jpg", label: "Bold Condensed Heart", desc: "Condensed uppercase, red heart accent, black & red news brand" },
  { file: "13-watercolor-spill.jpg", label: "Watercolor Spill", desc: "Soft watercolor box with fish & veggies, thin serif, pastel" },
  { file: "14-pixel-art-retro.jpg", label: "Pixel Art Retro", desc: "16-bit pixel box with steak & carrot, pixel font, green & orange" },
  { file: "15-woodcut-block-print.jpg", label: "Woodcut Block Print", desc: "Linocut style, fish & root veggies, bold black ink, sturdy serif" },
  { file: "16-art-deco-angular.jpg", label: "Art Deco Angular", desc: "Geometric deco box with wheat & fish motifs, gold & dark green" },
  { file: "17-kawaii-cute-box.jpg", label: "Kawaii Cute Box", desc: "Smiling box character holding shrimp & apple, pastel pink & mint" },
  { file: "18-rubber-stamp.jpg", label: "Rubber Stamp", desc: "Distressed circular stamp, box with meat & greens, dark red ink" },
  { file: "19-negative-space-lens.jpg", label: "Negative Space Lens", desc: "Magnifying glass with food box inside lens, dark blue, clever" },
  { file: "20-chalkboard-menu.jpg", label: "Chalkboard Menu", desc: "Chalk on dark green, doodle box/fish/veggies, farmstand feel" },
  { file: "21-isometric-3d-flat.jpg", label: "Isometric 3D Flat", desc: "Isometric open box with T-bone & broccoli, bright flat colors" },
  { file: "22-shield-crest.jpg", label: "Shield Crest", desc: "Heraldic shield, lobster & greens, ribbon banner, burgundy & green" },
  { file: "23-stipple-dot-art.jpg", label: "Stipple Dot Art", desc: "Pointillism/stipple box with salmon & avocado, black dots on white" },
  { file: "24-split-reveal.jpg", label: "Split Reveal", desc: "Half closed / half open box showing food, orange & teal split" },
  { file: "25-origami-paper.jpg", label: "Origami Paper", desc: "Paper-folded box with angular fish & pepper, coral & sage" },
  { file: "26-map-pin-finder.jpg", label: "Map Pin Finder", desc: "Location pin with box inside, food peeking out, blue & orange" },
  { file: "27-bauhaus-shapes.jpg", label: "Bauhaus Shapes", desc: "Primary geometric shapes as box + food, red/yellow/blue, avant-garde" },
  { file: "28-grocery-bag.jpg", label: "Grocery Bag", desc: "Paper bag with baguette/celery/meat, condensed bold text, warm brown" },
  { file: "29-neon-sign.jpg", label: "Neon Sign", desc: "Glowing neon tube text + box icon, electric pink & cyan" },
  { file: "30-botanical-illustration.jpg", label: "Botanical Illustration", desc: "Delicate herbs/radish/fish around box, italic serif, sage green ink" },
  { file: "31-compass-discovery.jpg", label: "Compass Discovery", desc: "Compass needle pointing at food box, sporty italic sans, navy & orange" },
  { file: "32-zen-brushstroke.jpg", label: "Zen Brushstroke", desc: "Single brushstroke box with ink wash fish, black & red accent, wabi-sabi" },
  { file: "33-stencil-street-art.jpg", label: "Stencil Street Art", desc: "Spray paint stencil letters, box with meat & veggies, black & green" },
  { file: "34-shipping-label.jpg", label: "Shipping Label", desc: "Delivery package with fork/knife label, typewriter monospace, kraft & black" },
  { file: "35-silhouette-cutout.jpg", label: "Silhouette Cutout", desc: "Dark box shape with food as negative white space, bold geometric font" },
  { file: "36-hexagon-tech.jpg", label: "Hexagon Tech", desc: "Hex badge with sushi/chicken/herbs, technical sans-serif, teal & gray" },
  { file: "37-ribbon-wrapped.jpg", label: "Ribbon Wrapped", desc: "Ribbon around box with ribs & veggies, name on ribbon, red & brown" },
  { file: "38-abstract-circles.jpg", label: "Abstract Circles", desc: "Three overlapping circles suggesting box + food, Mastercard-like, orange/green/blue" },
  { file: "39-checkmark-trust.jpg", label: "Checkmark Trust", desc: "Green check in box, shrimp & leaf, confident sans-serif, trust concept" },
  { file: "40-deli-label.jpg", label: "Deli Label", desc: "Stitched tag shape, friendly serif, ham/cheese/tomato, cream & brown" },
  { file: "41-cursor-click.jpg", label: "Cursor Click", desc: "Arrow clicking open box revealing food, sharp sans, electric blue & orange" },
  { file: "42-travel-sticker.jpg", label: "Travel Sticker", desc: "Luggage sticker shape, vintage poster font, crab & corn, teal & sunset" },
  { file: "43-recipe-card.jpg", label: "Recipe Card", desc: "Lined paper, handwriting font, doodle box with pork chop, blue pen ink" },
  { file: "44-gradient-mesh.jpg", label: "Gradient Mesh", desc: "Bold wide sans with orange-to-teal gradient, tiny box above i-dot" },
  { file: "45-plate-overhead.jpg", label: "Plate Overhead", desc: "Top-down plate with box center, shrimp/herbs/lemon rim, terracotta & olive" },
  { file: "46-blueprint-drafting.jpg", label: "Blueprint Drafting", desc: "Technical drawing with dimension arrows, cross-section food layers, blue ink" },
  { file: "47-sunset-steam.jpg", label: "Sunset Steam", desc: "Box silhouette on horizon, steam forming food shapes, amber & purple" },
  { file: "48-playing-card.jpg", label: "Playing Card", desc: "Ornate frame, mirrored fish/steak motifs, red & gold, regal" },
  { file: "49-fbf-monogram.jpg", label: "FBF Monogram", desc: "Custom lettermark: F=fork, B=box, F=fish tail, dark green" },
  { file: "50-price-tag-bargain.jpg", label: "Price Tag Bargain", desc: "Yellow price sticker with red burst, box with chicken, bold black" },
  { file: "051-wax-seal.jpg", label: "Wax Seal", desc: "Embossed wax seal with food box crest, elegant old-world authority" },
  { file: "052-emoji-flat-icon.jpg", label: "Emoji Flat Icon", desc: "Flat emoji-style icon with bold outlines, playful and universal" },
  { file: "053-letterpress-ticket.jpg", label: "Letterpress Ticket", desc: "Vintage letterpress ticket stub with typographic food box branding" },
  { file: "054-qr-code.jpg", label: "QR Code", desc: "Stylized QR code pattern forming the logo, modern digital identity" },
  { file: "055-postage-stamp.jpg", label: "Postage Stamp", desc: "Perforated stamp frame with food box illustration, collectible feel" },
  { file: "056-label-gun-tape.jpg", label: "Label Gun Tape", desc: "Price gun label tape aesthetic, retail-inspired typography" },
  { file: "057-constellation.jpg", label: "Constellation", desc: "Stars connected to form a food box shape, celestial discovery theme" },
  { file: "058-sports-badge.jpg", label: "Sports Badge", desc: "Athletic team badge style with food elements, competitive energy" },
  { file: "059-ransom-note.jpg", label: "Ransom Note", desc: "Cut-out mixed typography collage, edgy and attention-grabbing" },
  { file: "060-circuit-board.jpg", label: "Circuit Board", desc: "PCB trace patterns forming box and food, tech-forward approach" },
  { file: "061-grocery-receipt.jpg", label: "Grocery Receipt", desc: "Thermal receipt paper aesthetic with itemized food box details" },
  { file: "062-treasure-chest.jpg", label: "Treasure Chest", desc: "Open treasure chest overflowing with premium food items" },
  { file: "063-venn-diagram.jpg", label: "Venn Diagram", desc: "Overlapping circles of food, box, and discovery intersecting" },
  { file: "064-barcode.jpg", label: "Barcode", desc: "Stylized barcode with food silhouettes hidden in the lines" },
  { file: "065-hot-air-balloon.jpg", label: "Hot Air Balloon", desc: "Balloon made of food box delivering goods from above" },
  { file: "066-periodic-table.jpg", label: "Periodic Table", desc: "Element tile format with food box abbreviations, science-meets-food" },
  { file: "067-lightbulb-idea.jpg", label: "Lightbulb Idea", desc: "Lightbulb with food inside the glass, smart discovery concept" },
  { file: "068-parachute-delivery.jpg", label: "Parachute Delivery", desc: "Food box descending by parachute, fun airdrop delivery concept" },
  { file: "069-cutting-board.jpg", label: "Cutting Board", desc: "Wooden cutting board shape framing the brand, culinary foundation" },
  { file: "070-chef-toque.jpg", label: "Chef Toque", desc: "Classic chef hat with box and food elements, professional kitchen" },
  { file: "071-shopping-cart.jpg", label: "Shopping Cart", desc: "Cart filled with food boxes, retail convenience metaphor" },
  { file: "072-delivery-truck.jpg", label: "Delivery Truck", desc: "Side-view truck with food box branding, subscription delivery" },
  { file: "073-cornucopia.jpg", label: "Cornucopia", desc: "Horn of plenty overflowing with subscription food items" },
  { file: "074-bento-box.jpg", label: "Bento Box", desc: "Compartmentalized bento layout with varied food sections" },
  { file: "075-market-awning.jpg", label: "Market Awning", desc: "Striped market stall awning over food box display" },
  { file: "076-doorstep.jpg", label: "Doorstep", desc: "Food box sitting on a welcoming doorstep, home delivery warmth" },
  { file: "077-box-with-wings.jpg", label: "Box With Wings", desc: "Winged food box in flight, speed and freedom of delivery" },
  { file: "078-steam-aroma.jpg", label: "Steam Aroma", desc: "Rising steam wisps from a warm food box, appetite appeal" },
  { file: "079-gothic-blackletter.jpg", label: "Gothic Blackletter", desc: "Heavy blackletter typography with food motifs, bold and dramatic" },
  { file: "080-embroidered-patch.jpg", label: "Embroidered Patch", desc: "Stitched fabric patch with food box design, tactile and crafted" },
  { file: "081-mid-century-modern.jpg", label: "Mid-Century Modern", desc: "Atomic-age shapes and boomerang forms, retro sophistication" },
  { file: "082-art-nouveau.jpg", label: "Art Nouveau", desc: "Flowing organic curves with food and vine motifs, ornamental beauty" },
  { file: "083-memphis-design.jpg", label: "Memphis Design", desc: "Bold geometric shapes, squiggles, and bright 80s color palette" },
  { file: "084-swiss-international.jpg", label: "Swiss International", desc: "Clean grid-based Helvetica style, strict modernist typographic system" },
  { file: "085-pop-art-warhol.jpg", label: "Pop Art Warhol", desc: "Bright repeated food box motifs in Warhol pop art style" },
  { file: "086-mexican-folk-art.jpg", label: "Mexican Folk Art", desc: "Vibrant papel picado and folk patterns with food imagery" },
  { file: "087-highway-sign.jpg", label: "Highway Sign", desc: "Green highway road sign pointing to food box destination" },
  { file: "088-rocket-launch.jpg", label: "Rocket Launch", desc: "Food box as rocket blasting off, explosive growth energy" },
  { file: "089-leaf-wreath.jpg", label: "Leaf Wreath", desc: "Circular wreath of leaves and herbs framing the brand name" },
  { file: "090-clipboard-checklist.jpg", label: "Clipboard Checklist", desc: "Checked-off clipboard with food subscription items, organized" },
  { file: "091-polaroid-photo.jpg", label: "Polaroid Photo", desc: "Instant photo frame capturing a food box moment, nostalgic" },
  { file: "092-trophy-award.jpg", label: "Trophy Award", desc: "Winner trophy filled with food items, best-in-class positioning" },
  { file: "093-globe-world.jpg", label: "Globe World", desc: "World globe with food box overlay, global discovery reach" },
  { file: "094-matryoshka-doll.jpg", label: "Matryoshka Doll", desc: "Nesting doll revealing food layers inside, surprise and variety" },
  { file: "095-vintage-tv.jpg", label: "Vintage TV", desc: "Retro television screen displaying food box content, media feel" },
  { file: "096-spice-jar.jpg", label: "Spice Jar", desc: "Labeled spice jar shape with brand identity, pantry essential" },
  { file: "097-wooden-crate.jpg", label: "Wooden Crate", desc: "Rustic wooden produce crate with branded stencil lettering" },
  { file: "098-binoculars.jpg", label: "Binoculars", desc: "Binoculars with food visible in lenses, search and discover" },
  { file: "099-hourglass.jpg", label: "Hourglass", desc: "Hourglass with food flowing through, time-saving subscription" },
  { file: "100-stained-glass.jpg", label: "Stained Glass", desc: "Cathedral window style with colorful food mosaic panels" },
  { file: "101-sandwich-layers.jpg", label: "Sandwich Layers", desc: "Cross-section sandwich showing stacked ingredient layers" },
  { file: "102-key-and-lock.jpg", label: "Key And Lock", desc: "Key unlocking a food box, exclusive access and premium quality" },
  { file: "103-bicycle-basket.jpg", label: "Bicycle Basket", desc: "Bike basket loaded with food box items, local delivery charm" },
  { file: "104-picnic-basket.jpg", label: "Picnic Basket", desc: "Woven picnic basket with food peeking out, outdoor enjoyment" },
  { file: "105-pantry-shelf.jpg", label: "Pantry Shelf", desc: "Organized pantry shelf with curated food box selections" },
  { file: "106-farm-barn.jpg", label: "Farm Barn", desc: "Red barn with food box door, farm-to-table origin story" },
  { file: "107-stack-of-boxes.jpg", label: "Stack Of Boxes", desc: "Playful tower of stacked food boxes, variety and abundance" },
  { file: "108-sparkle-magic.jpg", label: "Sparkle Magic", desc: "Sparkling magic wand over food box, delightful surprise element" },
  { file: "109-hand-cupping.jpg", label: "Hand Cupping", desc: "Cupped hands presenting a food box, care and personal touch" },
  { file: "110-fortune-cookie.jpg", label: "Fortune Cookie", desc: "Cracked fortune cookie revealing food box message, luck and discovery" },
  { file: "111-thumbs-up.jpg", label: "Thumbs Up", desc: "Bold thumbs up with food box approval, trust and endorsement" },
  { file: "112-wifi-signal.jpg", label: "Wifi Signal", desc: "Signal waves emanating from food box, connected digital ordering" },
  { file: "113-crossword.jpg", label: "Crossword", desc: "Crossword puzzle grid spelling out food box terms, brainy fun" },
  { file: "114-subway-map.jpg", label: "Subway Map", desc: "Transit map style with food category routes and stops" },
  { file: "115-bookmark-ribbon.jpg", label: "Bookmark Ribbon", desc: "Ribbon bookmark marking a favorite food box, curated picks" },
  { file: "116-airmail-envelope.jpg", label: "Airmail Envelope", desc: "Red and blue striped airmail envelope with food box contents" },
  { file: "117-swiss-army-knife.jpg", label: "Swiss Army Knife", desc: "Multi-tool with food utensils, versatile all-in-one solution" },
  { file: "118-crown-food.jpg", label: "Crown Food", desc: "Royal crown adorned with food items, premium quality positioning" },
  { file: "119-rainbow-arc.jpg", label: "Rainbow Arc", desc: "Colorful rainbow arc over food box, variety and joy" },
  { file: "120-campfire.jpg", label: "Campfire", desc: "Campfire with food cooking above, outdoor warmth and community" },
  { file: "121-morse-code.jpg", label: "Morse Code", desc: "Dots and dashes spelling out brand, encoded communication style" },
  { file: "122-spyglass.jpg", label: "Spyglass", desc: "Pirate spyglass revealing food treasures, adventurous discovery" },
  { file: "123-spiral-notebook.jpg", label: "Spiral Notebook", desc: "Spiral-bound notebook page with food box sketches, planning" },
  { file: "124-toaster.jpg", label: "Toaster", desc: "Retro toaster popping up food items, quick and convenient" },
  { file: "125-pie-chart.jpg", label: "Pie Chart", desc: "Pie chart with food category segments, analytical comparison" },
  { file: "126-tangram-puzzle.jpg", label: "Tangram Puzzle", desc: "Geometric tangram pieces forming food box shape, clever assembly" },
  { file: "127-snow-globe.jpg", label: "Snow Globe", desc: "Snow globe containing a miniature food box scene, whimsical" },
  { file: "128-scope-viewfinder.jpg", label: "Scope Viewfinder", desc: "Camera viewfinder framing food box target, focused discovery" },
  { file: "129-lego-blocks.jpg", label: "Lego Blocks", desc: "Interlocking building blocks creating food box, customizable" },
  { file: "130-treasure-map.jpg", label: "Treasure Map", desc: "Aged treasure map with X marking the food box, adventure" },
  { file: "131-paper-plane.jpg", label: "Paper Plane", desc: "Folded paper airplane carrying food box message, light delivery" },
  { file: "132-anchor-nautical.jpg", label: "Anchor Nautical", desc: "Nautical anchor with food and rope details, steady reliability" },
  { file: "133-film-clapperboard.jpg", label: "Film Clapperboard", desc: "Movie clapperboard with food box scene info, cinematic" },
  { file: "134-dna-helix.jpg", label: "DNA Helix", desc: "Double helix with food molecules, personalized nutrition science" },
  { file: "135-speech-bubble.jpg", label: "Speech Bubble", desc: "Comic speech bubble containing food box, conversation starter" },
  { file: "136-kitchen-window.jpg", label: "Kitchen Window", desc: "Open kitchen window with food box on sill, homey invitation" },
  { file: "137-scissors-coupon.jpg", label: "Scissors Coupon", desc: "Scissors cutting a coupon for food box savings, deal-focused" },
  { file: "138-turntable-vinyl.jpg", label: "Turntable Vinyl", desc: "Vinyl record turntable with food groove pattern, curated taste" },
  { file: "139-conveyor-belt.jpg", label: "Conveyor Belt", desc: "Sushi-style conveyor delivering food boxes, automated selection" },
  { file: "140-food-tree.jpg", label: "Food Tree", desc: "Tree with food items as fruit and leaves, organic growth" },
  { file: "141-slot-machine.jpg", label: "Slot Machine", desc: "Casino slot reels showing food icons, lucky finds and variety" },
  { file: "142-microscope.jpg", label: "Microscope", desc: "Microscope examining food quality, detail-oriented inspection" },
  { file: "143-satellite-dish.jpg", label: "Satellite Dish", desc: "Satellite dish receiving food signals, wide-reaching discovery" },
  { file: "144-umbrella.jpg", label: "Umbrella", desc: "Umbrella sheltering a food box, protection and coverage" },
  { file: "145-ladder-peek.jpg", label: "Ladder Peek", desc: "Ladder leaning against box wall to peek inside, curiosity" },
  { file: "146-balance-scale.jpg", label: "Balance Scale", desc: "Justice scale weighing food options, fair comparison tool" },
  { file: "147-funnel-filter.jpg", label: "Funnel Filter", desc: "Funnel filtering food options down to best match, refined search" },
  { file: "148-fingerprint.jpg", label: "Fingerprint", desc: "Unique fingerprint pattern made of food items, personalized" },
  { file: "149-enso-zen.jpg", label: "Enso Zen", desc: "Zen ink circle brushstroke around food elements, mindful eating" },
  { file: "150-vs-comparison.jpg", label: "VS Comparison", desc: "Bold versus graphic comparing food boxes, head-to-head matchup" },
  { file: "151-stargazing.jpg", label: "Stargazing", desc: "Telescope pointed at food constellation, aspirational discovery" },
  { file: "152-abacus.jpg", label: "Abacus", desc: "Abacus beads as food items, counting value and comparison" },
  { file: "153-mixtape-cassette.jpg", label: "Mixtape Cassette", desc: "Cassette tape labeled with food box mix, curated selection" },
  { file: "154-domino-tile.jpg", label: "Domino Tile", desc: "Domino tile with food dots, chain reaction of great meals" },
  { file: "155-kaleidoscope.jpg", label: "Kaleidoscope", desc: "Kaleidoscope pattern from food shapes, infinite variety" },
  { file: "156-tetris.jpg", label: "Tetris", desc: "Falling tetris blocks as food items fitting together perfectly" },
  { file: "157-travel-suitcase.jpg", label: "Travel Suitcase", desc: "Vintage suitcase with food stickers, culinary journey" },
  { file: "158-maze.jpg", label: "Maze", desc: "Maze puzzle leading to food box at center, guided discovery" },
  { file: "159-dial-knob.jpg", label: "Dial Knob", desc: "Rotary dial tuning to food preferences, custom control" },
  { file: "160-open-book-popup.jpg", label: "Open Book Popup", desc: "Pop-up book with 3D food scene emerging from pages" },
  { file: "161-cuckoo-clock.jpg", label: "Cuckoo Clock", desc: "Cuckoo clock with food box popping out on schedule" },
  { file: "162-claw-machine.jpg", label: "Claw Machine", desc: "Arcade claw grabbing a food box prize, fun selection" },
  { file: "163-colander-strainer.jpg", label: "Colander Strainer", desc: "Colander filtering food choices, kitchen tool as brand mark" },
  { file: "164-semaphore-flags.jpg", label: "Semaphore Flags", desc: "Signal flags spelling food box, maritime communication" },
  { file: "165-marquee-theater.jpg", label: "Marquee Theater", desc: "Theater marquee announcing food box features, showtime" },
  { file: "166-raindrop.jpg", label: "Raindrop", desc: "Water drop with food reflection inside, fresh and pure" },
  { file: "167-quilt-patchwork.jpg", label: "Quilt Patchwork", desc: "Patchwork quilt squares with food patterns, handcrafted warmth" },
  { file: "168-dashboard-gauge.jpg", label: "Dashboard Gauge", desc: "Speedometer gauge measuring food value, performance metrics" },
  { file: "169-pirate-spyglass.jpg", label: "Pirate Spyglass", desc: "Pirate with spyglass spotting food treasure, swashbuckling fun" },
  { file: "170-pinball.jpg", label: "Pinball", desc: "Pinball machine with food bumpers and flippers, retro gaming" },
  { file: "171-lighthouse.jpg", label: "Lighthouse", desc: "Lighthouse beam guiding to food boxes, beacon of discovery" },
  { file: "172-vending-machine.jpg", label: "Vending Machine", desc: "Vending machine dispensing food boxes, instant access" },
  { file: "173-pencil-drawing.jpg", label: "Pencil Drawing", desc: "Hand-sketched pencil illustration style, artisan craftsmanship" },
  { file: "174-solar-system.jpg", label: "Solar System", desc: "Planets orbiting a food box sun, universe of options" },
  { file: "175-wristwatch.jpg", label: "Wristwatch", desc: "Watch face with food icons at each hour, timely delivery" },
  { file: "176-mosaic-tile.jpg", label: "Mosaic Tile", desc: "Small tile mosaic forming food box portrait, detailed artistry" },
  { file: "177-toolbox.jpg", label: "Toolbox", desc: "Toolbox filled with kitchen utensils and food, practical utility" },
  { file: "178-catapult.jpg", label: "Catapult", desc: "Medieval catapult launching food box, powerful delivery force" },
  { file: "179-snowflake.jpg", label: "Snowflake", desc: "Unique snowflake pattern with food elements, one-of-a-kind" },
  { file: "180-typewriter.jpg", label: "Typewriter", desc: "Vintage typewriter printing food box story, editorial charm" },
  { file: "181-jigsaw-puzzle.jpg", label: "Jigsaw Puzzle", desc: "Puzzle pieces forming food box image, everything fits together" },
  { file: "182-watering-can.jpg", label: "Watering Can", desc: "Watering can nurturing food growth, care and cultivation" },
  { file: "183-gumball-machine.jpg", label: "Gumball Machine", desc: "Gumball machine dispensing colorful food spheres, fun variety" },
  { file: "184-megaphone.jpg", label: "Megaphone", desc: "Megaphone broadcasting food box deals, loud and clear" },
  { file: "185-gift-bow.jpg", label: "Gift Bow", desc: "Wrapped gift with bow on food box, special occasion treat" },
  { file: "186-ship-in-bottle.jpg", label: "Ship In Bottle", desc: "Miniature food scene inside glass bottle, precious and detailed" },
  { file: "187-origami-crane.jpg", label: "Origami Crane", desc: "Paper crane folded from food box packaging, elegant simplicity" },
  { file: "188-charcuterie.jpg", label: "Charcuterie", desc: "Artfully arranged charcuterie board as brand mark, gourmet curation" },
  { file: "189-mailbox.jpg", label: "Mailbox", desc: "Mailbox overflowing with food box deliveries, anticipation" },
  { file: "190-zodiac-wheel.jpg", label: "Zodiac Wheel", desc: "Zodiac wheel with food symbols at each sign, cosmic match" },
  { file: "191-ferris-wheel.jpg", label: "Ferris Wheel", desc: "Ferris wheel cars carrying food boxes, carnival excitement" },
  { file: "192-fishing-reel.jpg", label: "Fishing Reel", desc: "Fishing reel reeling in a food box catch, great find" },
  { file: "193-constructivist.jpg", label: "Constructivist", desc: "Bold Soviet constructivist propaganda style, striking angles" },
  { file: "194-rubiks-cube.jpg", label: "Rubiks Cube", desc: "Rubiks cube faces as food categories, satisfying solution" },
  { file: "195-periscope.jpg", label: "Periscope", desc: "Submarine periscope spotting food boxes, hidden gem finder" },
  { file: "196-magician-hat.jpg", label: "Magician Hat", desc: "Magic hat pulling out food box surprise, wonder and delight" },
  { file: "197-sundial.jpg", label: "Sundial", desc: "Sundial casting food shadow, timeless quality and tradition" },
  { file: "198-garden-gate.jpg", label: "Garden Gate", desc: "Garden gate opening to food paradise, inviting entrance" },
  { file: "199-torii-gate.jpg", label: "Torii Gate", desc: "Japanese torii gate framing food box, sacred discovery path" },
  { file: "200-minimal-i-dot.jpg", label: "Minimal I-Dot", desc: "Minimalist typography with food box replacing the i-dot, subtle" },
];

export default function LogoGalleryPage() {
  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-extrabold text-neutral-900">Logo Gallery</h1>
        <p className="mt-2 text-neutral-600">
          200 unique logo directions for FoodBoxFinder
        </p>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-5 gap-5">
        {logos.map((logo, i) => (
          <div
            key={logo.file}
            className="group relative rounded-xl border border-neutral-200 bg-white overflow-hidden shadow-sm hover:shadow-lg hover:ring-2 hover:ring-primary-300 transition-all"
          >
            <div className="relative aspect-[3/2]">
              <Image
                src={`/assets/logos/concepts/${logo.file}`}
                alt={`#${i + 1} ${logo.label}`}
                fill
                sizes="(max-width: 640px) 50vw, (max-width: 768px) 33vw, (max-width: 1280px) 25vw, 20vw"
                className="object-contain p-2"
              />
              <span className="absolute top-1.5 left-1.5 text-[11px] font-bold font-mono text-white bg-black/60 px-2 py-0.5 rounded">
                #{i + 1}
              </span>
            </div>
            <div className="px-3 pb-3">
              <p className="text-xs font-bold text-neutral-900 truncate">{logo.label}</p>
              <p className="text-[11px] text-neutral-500 line-clamp-2 leading-tight mt-0.5">{logo.desc}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
